# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyaz < Formula
  desc "A terminal-based UI application for interacting with Azure DevOps"
  homepage "https://github.com/aldnav/lazyaz"
  version "0.0.2"

  on_macos do
    url "https://github.com/aldnav/lazyaz/releases/download/0.0.2/lazyaz_Darwin_all.tar.gz"
    sha256 "2e0dba5cb01927ba127c647ebfc587e2ca7e7371811cd8b7b47bb035fcac8584"

    def install
      bin.install "lazyaz"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aldnav/lazyaz/releases/download/0.0.2/lazyaz_Linux_x86_64.tar.gz"
        sha256 "109f368898ee7f154b1dbe002708cb7f19aedc27e332a8c0b73704f636ece4b6"

        def install
          bin.install "lazyaz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aldnav/lazyaz/releases/download/0.0.2/lazyaz_Linux_arm64.tar.gz"
        sha256 "54414d13e38e55148e5f16e00db40a0ebb2a71ba5578430f5e78d67ec776be71"

        def install
          bin.install "lazyaz"
        end
      end
    end
  end
end
