# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyaz < Formula
  desc "A terminal-based UI application for interacting with Azure DevOps"
  homepage "https://github.com/aldnav/lazyaz"
  version "0.0.1"

  on_macos do
    url "https://github.com/aldnav/lazyaz/releases/download/0.0.1/lazyaz_Darwin_all.tar.gz"
    sha256 "00767f3b08619783930fe9c1c9576c699a82b3d76e5ed90b807cf776c6577e5b"

    def install
      bin.install "lazyaz"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aldnav/lazyaz/releases/download/0.0.1/lazyaz_Linux_x86_64.tar.gz"
        sha256 "a30b836aac659bbc2a0f7a020962bedc5dd202230494f0b16b11f424b2e08a08"

        def install
          bin.install "lazyaz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aldnav/lazyaz/releases/download/0.0.1/lazyaz_Linux_arm64.tar.gz"
        sha256 "6a89e49a35ab9fc1916125744ed5b353e60f5ef4844e365ecabf38c056230711"

        def install
          bin.install "lazyaz"
        end
      end
    end
  end
end
