# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyaz < Formula
  desc "Terminal-based UI application for interacting with Azure DevOps"
  homepage "https://github.com/aldnav/lazyaz"
  version "0.0.3"

  on_macos do
    url "https://github.com/aldnav/lazyaz/releases/download/0.0.3/lazyaz_Darwin_all.tar.gz"
    sha256 "aef9f5ef6ed40824174cab3bb5e2f796eebf8849889a87c1c570d2b5b0e3ca8a"

    def install
      bin.install "lazyaz"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aldnav/lazyaz/releases/download/0.0.3/lazyaz_Linux_x86_64.tar.gz"
        sha256 "e60dbbd3b3c6ad98482560fef800cc0ced0727cf9e05a66756508b556f1f0eaa"

        def install
          bin.install "lazyaz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/aldnav/lazyaz/releases/download/0.0.3/lazyaz_Linux_arm64.tar.gz"
        sha256 "4977c0d4a1816bcac8cfedec50766d1f426922c45b535bf16829b9d01917765c"

        def install
          bin.install "lazyaz"
        end
      end
    end
  end
end
